### ISSUE TITLE
[stereo_view] Low number of synchronized left/right/disparity triplets received.

### ISSUE THREAD

**Issue by codexsameen** [samisnotinsane/arq-teleop-robot#3]
I wish to see a stereo feed from my stereo camera in Gazebo. The [image_view](http://wiki.ros.org/image_view#stereo_view) package seems to be ideal for doing this. My camera topics are as follows:
```
/stereo/left/camera_info
/stereo/left/image_raw
/stereo/right/camera_info
/stereo/right/image_raw
```
Running image_view with the following command:
`rosrun image_view stereo_view stereo:=/stereo image:=image_raw`
three windows appear: left, disparity and right. They remain 'frozen'. After a while, the following warning appears:
```
Left images received:      432 (topic '/stereo/left/image_raw')
Right images received:     433 (topic '/stereo/right/image_raw')
Disparity images received: 0 (topic '/stereo/disparity')
Synchronized triplets: 0

Possible issues:
	* stereo_image_proc is not running.
	  Does `rosnode info /stereo_view_1517406567385015137` show any connections?
	* The cameras are not synchronized.
	  Try restarting stereo_view with parameter _approximate_sync:=True
	* The network is too slow. One or more images are dropped from each triplet.
	  Try restarting stereo_view, increasing parameter 'queue_size' (currently 5)
```
This error keeps recurring at the same time interval indefinitely (until process is killed).

**Comment by codexsameen** [comment]
Accounting for inexact synchronisation by setting approximate_sync parameter to true and a large queue size:
`rosrun image_view stereo_view stereo:=/stereo image:=image_raw _approximate_sync:=True _queue_size:=800`

**stdio dump:**
```
[ WARN] [1517408414.095487294]: There is a delay between when the camera drivers publish the raw images and when stereo_image_proc publishes the computed point cloud. stereo_view may fail to synchronize these topics without a large queue_size.
[ INFO] [1517408414.240142761]: Subscribing to:
	* /stereo/left/image_raw
	* /stereo/right/image_raw
	* /stereo/disparity
[ WARN] [1517408429.275285391, 3967.225000000]: [stereo_view] Low number of synchronized left/right/disparity triplets received.
Left images received:      445 (topic '/stereo/left/image_raw')
Right images received:     445 (topic '/stereo/right/image_raw')
Disparity images received: 0 (topic '/stereo/disparity')
Synchronized triplets: 0
Possible issues:
	* stereo_image_proc is not running.
	  Does `rosnode info /stereo_view_1517408414092739094` show any connections?
	* The cameras are not synchronized.
	  Try restarting stereo_view with parameter _approximate_sync:=True
	* The network is too slow. One or more images are dropped from each triplet.
	  Try restarting stereo_view, increasing parameter 'queue_size' (currently 800)

```

**Comment by gokhansolak** [comment]
I think I had some progress on it. When you run first:
`ROS_NAMESPACE=stereo rosrun stereo_image_proc stereo_image_proc _approximate_sync:=true`

And then call the image_view:
`rosrun image_view stereo_view stereo:=/stereo age:=image_raw _approximate_sync:=True _queue_size:=80`

Then the disparity window shows some strange output. But doesn't freeze as in picture:
![weird pixels](https://i.imgur.com/62lg6WN.png "https://imgur.com/a/ztPdZ")

I found this solution [here](https://github.com/ros-perception/image_pipeline/issues/130).
